### ISSUE TITLE
Request for Help with M2cai16-workflow Dataset

### ISSUE THREAD

**Issue by QYixuan** [xjgaocs/Trans-SVNet#14]
Hi, I have recently tried to start comparing the results of your work on the M2cai16 dataset, but I have found that the download link is no longer available on the official website, and I can only receive the download link for the m2cai16-tool dataset. Would you please share the download link of m2cai16-workflow dataset? Thank you very much!

**Comment by mubashir804** [comment]
I have facing the issue to find M2cai16 workflow dataset. And I have to work for academic purpose If you have download link kindly share with me. Thank You very much!
